a = int('5')
b = str(5)
c = range(5)
d = complex(5)
e = [5, 6, "H"]
f = ("This is a tuple", True)
g = float(a)
h = {"It's a set", 4.1}
i = {42: "This is a dict", "N": "S"}
j = 5 > 0
k = frozenset(h)
m = b"Something"
n = bytearray(7)
o = memoryview(m)
p = None

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
print(k)
print(m)
print(n)
print(o)
print(p)
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))
print(type(i))
print(type(j))
print(type(k))
print(type(m))
print(type(n))
print(type(o))
print(type(p))
